#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="${1:?usage: reconcile-runtime-db-role.sh <instance-env-file>}"
[[ -f "$ENV_FILE" ]] || { echo "Missing environment file: $ENV_FILE" >&2; exit 1; }
set -a
# The instance environment file is generated by bootstrap/provision and is
# already sourced by deploy-prod.sh for migrations.
source "$ENV_FILE"
set +a

if [[ -n "${DATABASE_URL_APP:-}" ]]; then
  mapfile -d '' -t app_url_parts < <(python3 - <<'PY'
import os
import sys
from urllib.parse import unquote, urlparse

url = urlparse(os.environ['DATABASE_URL_APP'])
if url.scheme not in ('postgres', 'postgresql') or not url.username or not url.password or not url.path:
    sys.exit('Invalid DATABASE_URL_APP')
for value in (unquote(url.username), unquote(url.password), url.path.lstrip('/')):
    sys.stdout.buffer.write(value.encode() + b'\0')
PY
  )
  DB_USER_APP="${DB_USER_APP:-${app_url_parts[0]:-}}"
  DB_PASS_APP="${DB_PASS_APP:-${app_url_parts[1]:-}}"
  [[ "${app_url_parts[2]:-}" == "${DB_NAME:-}" ]] || {
    echo 'DB_NAME does not match DATABASE_URL_APP database' >&2; exit 1;
  }
fi

for name in DB_NAME DB_USER DB_USER_APP; do
  value="${!name:-}"
  [[ "$value" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || { echo "Invalid $name" >&2; exit 1; }
done
[[ -n "${DB_PASS_APP:-}" ]] || { echo 'DB_PASS_APP is required' >&2; exit 1; }

sudo -u postgres psql -X -v ON_ERROR_STOP=1 -d "$DB_NAME" \
  -v app_role="$DB_USER_APP" -v app_pass="$DB_PASS_APP" \
  -v migrate_role="$DB_USER" -v db_name="$DB_NAME" <<'SQL'
SELECT format('CREATE ROLE %I LOGIN NOBYPASSRLS NOSUPERUSER PASSWORD %L', :'app_role', :'app_pass')
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'app_role') \gexec
SELECT format('ALTER ROLE %I LOGIN NOBYPASSRLS NOSUPERUSER PASSWORD %L', :'app_role', :'app_pass') \gexec
SELECT format('ALTER ROLE %I RESET "app.service"', :'app_role') \gexec
SELECT format('GRANT CONNECT ON DATABASE %I TO %I', :'db_name', :'app_role') \gexec
SELECT format('GRANT USAGE ON SCHEMA public TO %I', :'app_role') \gexec
SELECT format('REVOKE SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public FROM %I', :'app_role') \gexec
SELECT format('GRANT SELECT,INSERT,UPDATE,DELETE ON %I.%I TO %I', 'public', c.relname, :'app_role')
FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
WHERE n.nspname='public' AND c.relkind IN ('r','p') AND c.relname=ANY(ARRAY['ActiveIndexGeneration','ArtifactDependency','ArtifactManifest','AuditLog','AuthorizationState','BlockArtifact','BrainChangeEvent','BrainDerivedPage','BrainMaintenanceRun','BrainOperationLog','BrainRepo','BrainScope','BrainScopeMember','BrainSource','BrainSourceDocument','BrainSourceMember','BrainTopic','ChatRun','Chunk','ChunkLexicalDoc','ChunkSparseEmbedding','Citation','CompileJob','ConnectorRun','ConnectorSource','ContextualPrefixCache','Conversation','Document','DocumentAcl','DocumentVersion','DocumentVersionLink','EmbeddingModelState','EnrichmentStage','FeedbackCase','GenerationVector','GraphCommunity','GraphEntity','GraphProjectionInput','GraphRelation','IndexGeneration','IndustryGrant','KbAdmin','KbLexicalStat','KbModelOverride','KnowledgeBase','LateContextVector','LexicalTermStat','Message','ModelArtifactCache','ModelConfig','ModelProvider','OrgAdmin','OrgNode','OriginalBlockSnapshot','RaptorNode','Role','SemanticCache','SystemSetting','User','UserCredential','UserOrg','UserRole']) \gexec
-- Quota mutation goes through app_admit_model_call() (SECURITY DEFINER), but
-- the recovery sweep also prunes expired buckets with a plain
-- `DELETE ... WHERE period < ...`, and a WHERE clause needs SELECT. Granting
-- SELECT is safe: the table's only policy is `app_is_service()`, so RLS still
-- hides the rows outside a service context.
SELECT format('GRANT SELECT,DELETE ON public."ModelQuotaBucket" TO %I', :'app_role') \gexec
SELECT format('GRANT USAGE,SELECT,UPDATE ON ALL SEQUENCES IN SCHEMA public TO %I', :'app_role') \gexec
SELECT format('ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA public REVOKE SELECT,INSERT,UPDATE,DELETE ON TABLES FROM %I', :'migrate_role', :'app_role') \gexec
SELECT format('ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA public GRANT USAGE,SELECT,UPDATE ON SEQUENCES TO %I', :'migrate_role', :'app_role') \gexec
SQL
