import { execFile } from "node:child_process";
import { randomUUID } from "node:crypto";
import { Logger } from "@nestjs/common";
import { mkdir, mkdtemp, readdir, rename, rm } from "node:fs/promises";
import { dirname, join } from "node:path";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);
const logger = new Logger("OfficeConverter");

export type OfficeConversionMode = "unoserver" | "soffice-fallback";

export interface OfficeConversionResult {
  pdfPath: string;
  mode: OfficeConversionMode;
  durationMs: number;
}

export function buildUnoconvertArgs(
  sourcePath: string,
  outputPath: string,
): string[] {
  return [
    "--host",
    process.env.UNOSERVER_HOST || "127.0.0.1",
    "--port",
    process.env.UNOSERVER_PORT || "2003",
    sourcePath,
    outputPath,
    "--convert-to",
    "pdf",
  ];
}

// A per-invocation UserInstallation profile is what makes concurrent cold
// soffice calls safe at all: the default shared profile is guarded by a lock,
// so parallel conversions on one host serialize or fail outright.
export function buildSofficeArgs(
  sourcePath: string,
  outDir: string,
  profileDir: string,
): string[] {
  return [
    `-env:UserInstallation=file://${profileDir}`,
    "--headless",
    "--convert-to",
    "pdf",
    sourcePath,
    "--outdir",
    outDir,
  ];
}

async function runUnoconvert(
  sourcePath: string,
  outputPath: string,
): Promise<string | null> {
  if (process.env.OFFICE_PREVIEW_UNOSERVER === "0") return null;
  const bin = process.env.UNOSERVER_CONVERT_BIN || "unoconvert";
  try {
    await execFileAsync(bin, buildUnoconvertArgs(sourcePath, outputPath), {
      timeout: Number(process.env.UNOSERVER_TIMEOUT_MS || 60000),
    });
    return outputPath;
  } catch (error) {
    // Missing binary or listener down is an expected degraded state, not an
    // error: the caller must fall through to the isolated soffice fallback.
    logger.debug(
      `unoconvert unavailable (${(error as Error).message}); falling back to soffice`,
    );
    return null;
  }
}

async function runSoffice(
  sourcePath: string,
  outDir: string,
  profileDir: string,
): Promise<string | null> {
  await execFileAsync("soffice", buildSofficeArgs(sourcePath, outDir, profileDir), {
    timeout: Number(process.env.SOFFICE_TIMEOUT_MS || 120000),
  });
  const files = await readdir(outDir);
  const pdf = files.find((f) => f.toLowerCase().endsWith(".pdf"));
  return pdf ? join(outDir, pdf) : null;
}

export interface ConverterRunners {
  unoconvert: typeof runUnoconvert;
  soffice: typeof runSoffice;
}

const defaultRunners: ConverterRunners = { unoconvert: runUnoconvert, soffice: runSoffice };

/**
 * Convert an Office document (ppt/pptx/doc/docx/xls/…) to PDF next to the
 * caller's cache location. Converts in a temp directory on the same
 * filesystem, then renames, so a crashed conversion never leaves a partial
 * file at the cached path.
 */
export async function convertOfficeToPdf(
  sourcePath: string,
  targetPdfPath: string,
  runners: ConverterRunners = defaultRunners,
): Promise<OfficeConversionResult> {
  const startedAt = Date.now();
  const workDir = await mkdtemp(
    join(dirname(sourcePath), `.convert_temp_${Date.now()}_`),
  );
  try {
    let mode: OfficeConversionMode = "unoserver";
    let produced =
      (await runners.unoconvert(sourcePath, join(workDir, "preview.pdf"))) ??
      null;
    if (!produced) {
      mode = "soffice-fallback";
      produced = await runners.soffice(
        sourcePath,
        workDir,
        join(workDir, `lo_profile_${randomUUID().slice(0, 8)}`),
      );
    }
    if (!produced) throw new Error("No PDF generated by office converter");

    await mkdir(dirname(targetPdfPath), { recursive: true });
    await rename(produced, targetPdfPath);
    const durationMs = Date.now() - startedAt;
    logger.log(`Office→PDF via ${mode} in ${durationMs}ms: ${sourcePath}`);
    return { pdfPath: targetPdfPath, mode, durationMs };
  } finally {
    await rm(workDir, { recursive: true, force: true }).catch(() => undefined);
  }
}
