import { mkdtemp, mkdir, readFile, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  buildSofficeArgs,
  buildUnoconvertArgs,
  convertOfficeToPdf,
  type ConverterRunners,
} from "./office-converter";

/**
 * The preview pipeline must survive unoserver being absent (fresh installs,
 * stopped listener) by falling back to a profile-isolated cold soffice call —
 * and that fallback must carry its own UserInstallation profile, because the
 * default shared profile lock is what makes concurrent conversions fail.
 */

describe("buildUnoconvertArgs", () => {
  it("targets the local listener with overridable host and port", () => {
    process.env.UNOSERVER_HOST = "10.1.2.3";
    process.env.UNOSERVER_PORT = "2103";
    try {
      expect(
        buildUnoconvertArgs("/tmp/a.pptx", "/tmp/out/preview.pdf"),
      ).toEqual([
        "--host",
        "10.1.2.3",
        "--port",
        "2103",
        "/tmp/a.pptx",
        "/tmp/out/preview.pdf",
        "--convert-to",
        "pdf",
      ]);
    } finally {
      delete process.env.UNOSERVER_HOST;
      delete process.env.UNOSERVER_PORT;
    }
  });
});

describe("buildSofficeArgs", () => {
  it("isolates the profile so parallel conversions cannot contend on one lock", () => {
    const args = buildSofficeArgs("/tmp/a.pptx", "/tmp/out", "/tmp/profile1");
    expect(args[0]).toBe("-env:UserInstallation=file:///tmp/profile1");
    expect(args).toEqual(
      expect.arrayContaining(["--headless", "--convert-to", "pdf"]),
    );
  });
});

describe("convertOfficeToPdf", () => {
  let dir: string;
  let source: string;
  let target: string;

  beforeEach(async () => {
    dir = await mkdtemp(join(tmpdir(), "office-converter-spec-"));
    source = join(dir, "deck.pptx");
    target = join(dir, "converted_preview_v1.pdf");
    await writeFile(source, "fake-office-bytes");
  });

  afterEach(async () => {
    await rm(dir, { recursive: true, force: true }).catch(() => undefined);
  });

  const fakeProducing = (
    runners: Partial<ConverterRunners>,
  ): ConverterRunners => ({
    unoconvert: async () => null,
    soffice: async () => null,
    ...runners,
  });

  it("uses unoserver output when available and renames it to the cache path", async () => {
    const runners = fakeProducing({
      unoconvert: async (_src, out) => {
        await mkdir(join(out, ".."), { recursive: true });
        await writeFile(out, "%PDF-uno");
        return out;
      },
    });
    const result = await convertOfficeToPdf(source, target, runners);
    expect(result.mode).toBe("unoserver");
    expect(result.pdfPath).toBe(target);
    expect(await readFile(target, "utf8")).toBe("%PDF-uno");
  });

  it("falls back to profile-isolated soffice when unoserver yields nothing", async () => {
    const sofficeProfileArgs: string[][] = [];
    const runners = fakeProducing({
      soffice: async (_src, outDir, profileDir) => {
        sofficeProfileArgs.push(
          buildSofficeArgs(_src, outDir, profileDir),
        );
        const pdf = join(outDir, "deck.pdf");
        await writeFile(pdf, "%PDF-cold");
        return pdf;
      },
    });
    const result = await convertOfficeToPdf(source, target, runners);
    expect(result.mode).toBe("soffice-fallback");
    expect(sofficeProfileArgs[0][0]).toMatch(/^-env:UserInstallation=file:\/\//);
    expect(await readFile(target, "utf8")).toBe("%PDF-cold");
  });

  it("fails loudly when neither converter produces a PDF", async () => {
    await expect(
      convertOfficeToPdf(source, target, fakeProducing({})),
    ).rejects.toThrow("No PDF generated by office converter");
  });

  it("cleans up the conversion workdir", async () => {
    const before = await mkdtemp(join(tmpdir(), "watch-parent-"));
    const nestedSource = join(before, "nested", "doc.docx");
    await mkdir(join(before, "nested"), { recursive: true });
    await writeFile(nestedSource, "x");
    const runners = fakeProducing({
      unoconvert: async (_src, out) => {
        await writeFile(out, "%PDF");
        return out;
      },
    });
    await convertOfficeToPdf(
      nestedSource,
      join(before, "nested", "cache.pdf"),
      runners,
    );
    const { readdir } = await import("node:fs/promises");
    const leftovers = (await readdir(join(before, "nested"))).filter((f) =>
      f.startsWith(".convert_temp_"),
    );
    expect(leftovers).toEqual([]);
    await rm(before, { recursive: true, force: true });
  });
});
